version: "3"
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
